[workspace]
resolver = "2"
members = [
    "crates/nucleus-db",
    "crates/nucleus-compiler",
    "crates/nucleus-cli",
    "crates/nucleus-lsp",
    "crates/nucleus-itm",
    "crates/nucleus-trace",
    "crates/nucleus-hil",
    "crates/nucleus-test-sdk",
    "crates/nucleus-history",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/harshverma27/nucleus"
authors = ["Harsh Verma"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
